# Generated by Django 3.0.2 on 2020-01-15 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EGID', models.IntegerField(default=0)),
                ('EDID', models.IntegerField(default=0)),
                ('GDEKT', models.CharField(default='', max_length=50)),
                ('GDENR', models.PositiveIntegerField(default=99)),
                ('GDENAME', models.CharField(default='', max_length=50)),
                ('STRNAME', models.CharField(default='', max_length=50)),
                ('DEINR', models.CharField(default='', max_length=50)),
                ('PLZ4', models.IntegerField(default=-99)),
                ('PLZZ', models.IntegerField(default=-99)),
                ('PLZNAME', models.CharField(default='', max_length=50)),
                ('GKODE', models.FloatField(default=-99)),
                ('GKODN', models.FloatField(default=-99)),
                ('STRSP', models.CharField(default='', max_length=2)),
                ('STRNAME_DEINR', models.CharField(default='', max_length=50)),
                ('COORDINATES', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
