# Generated by Django 3.0.2 on 2020-01-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200115_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresse',
            new_name='Address',
        ),
    ]
