# Generated by Django 3.0.2 on 2020-01-15 13:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20200115_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='COORDINATES',
            field=django.contrib.gis.db.models.fields.PointField(srid=2056),
        ),
    ]
