# Generated by Django 3.0.2 on 2020-01-21 15:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_remove_address_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='COORDINATES',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=2056),
            preserve_default=False,
        ),
    ]
