# Generated by Django 3.0.2 on 2020-01-21 15:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_address_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='COORDINATES',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2056),
        ),
    ]
