# Generated by Django 3.0.2 on 2020-01-21 15:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_auto_20200121_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='COORDINATES',
            field=django.contrib.gis.db.models.fields.PointField(srid=2056),
        ),
    ]
