# Generated by Django 3.0.2 on 2020-01-14 15:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STRNAME_DEINR', models.CharField(max_length=50)),
                ('COORDINATES', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
