# Generated by Django 3.0.2 on 2020-01-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='STRNAME_DEINR',
        ),
    ]
