# Generated by Django 3.0.2 on 2020-01-14 16:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0002_remove_addresses_strname_deinr'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='DEINR',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='addresses',
            name='EDID',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='addresses',
            name='EGID',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='addresses',
            name='GDEKT',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='addresses',
            name='GDENAME',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='addresses',
            name='GDENR',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='addresses',
            name='GKODE',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='addresses',
            name='GKODN',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='addresses',
            name='PLZ4',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='addresses',
            name='PLZNAME',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='addresses',
            name='PLZZ',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='addresses',
            name='STRNAME',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='addresses',
            name='STRNAME_DEINR',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='addresses',
            name='STRSP',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='COORDINATES',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
        ),
    ]
