# Generated by Django 3.0.2 on 2020-01-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0003_auto_20200114_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='EDID',
            field=models.PositiveIntegerField(default='99'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='EGID',
            field=models.PositiveIntegerField(default='99'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='GDENR',
            field=models.PositiveIntegerField(default='99'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='GKODE',
            field=models.FloatField(default='99'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='GKODN',
            field=models.FloatField(default='99'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='PLZ4',
            field=models.PositiveIntegerField(default='99'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='PLZZ',
            field=models.PositiveIntegerField(default='99'),
        ),
    ]
