# Generated by Django 3.0.2 on 2020-01-14 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0005_auto_20200114_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='COORDINATES',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
