# Generated by Django 3.0.2 on 2020-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0006_auto_20200114_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='EDID',
            field=models.IntegerField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='EGID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='PLZ4',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='PLZZ',
            field=models.IntegerField(default=99),
        ),
    ]
