# Generated by Django 3.0.2 on 2020-01-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0008_auto_20200114_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='EDID',
        ),
        migrations.AlterField(
            model_name='addresses',
            name='EGID',
            field=models.IntegerField(),
        ),
    ]
