# Generated by Django 3.0.2 on 2020-01-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0009_auto_20200114_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='EGID',
        ),
    ]
