# Generated by Django 3.0.2 on 2020-01-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0012_auto_20200114_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='EDID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='EGID',
            field=models.FloatField(),
        ),
    ]
