# Generated by Django 3.0.2 on 2020-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0014_auto_20200114_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='EGID',
            field=models.IntegerField(default=0),
        ),
    ]
