# Generated by Django 3.0.2 on 2020-01-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regbl_db', '0016_auto_20200114_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='EDID',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='EGID',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='GDEKT',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='GDENAME',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='GDENR',
        ),
    ]
